version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "backend"]
    commit-message:
      prefix: "chore(backend-deps)"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "frontend"]
    commit-message:
      prefix: "chore(frontend-deps)"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "chore(ci)"
